language: node_js
node_js:
- stable
env:
- SERVER_ADDRESS: s3.mydevil.net
before_script:
- npm ci
script:
- npm run build
before_install:
- openssl aes-256-cbc -K $encrypted_dfdcfd5172af_key -iv $encrypted_dfdcfd5172af_iv
  -in deploy_key.enc -out ./deploy_key -d
